spring:
  application:
    name: notas
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    password: password
  h2:
    console:
      enabled: 'true'
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

jwt:
  expiration: 60000
  secret: t6EvWKthGbAPKmC0l+vMnGSqpq+0f+vA/emfyWPlMJc=